version: 2
updates:
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: daily
          time: "06:00"
      versioning-strategy: increase
      open-pull-requests-limit: 20
      commit-message:
          prefix: "chore(deps): "
      allow:
          - dependency-type: all
      labels: ["dependencies"]

    - package-ecosystem: "github-actions"
      directory: "/"
      commit-message:
          prefix: "chore(deps): "
      schedule:
          interval: daily
          time: "06:00"
      open-pull-requests-limit: 20
      labels: ["dependencies"]
