name: Danger
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Danger JS
      run: |
        npm install danger
        node node_modules/.bin/danger ci --base master
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}