name: Release
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Download box
      run: wget https://github.com/humbug/box/releases/download/3.11.0/box.phar
    
    - name: Remove dev deps
      run: composer install --no-dev

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      
    - name: Set version string
      run: sed -i -e "s/__VERSION__/${{ steps.get_version.outputs.VERSION }}/g" src/Application.php
  
    - name: Build phar
      run: php box.phar compile
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
      
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: frosh-plugin-upload.phar
        asset_name: frosh-plugin-upload.phar
        asset_content_type: application/octet-stream

    - name: Login into Docker Registery
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Login into Github Docker Registery
      run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Build image and push
      run: |
        docker build -t friendsofshopware/plugin-uploader:${{ steps.get_version.outputs.VERSION }} .
        docker build -t ghcr.io/friendsofshopware/plugin-uploader:${{ steps.get_version.outputs.VERSION }} .
        docker build -t friendsofshopware/plugin-uploader .
        docker build -t ghcr.io/friendsofshopware/plugin-uploader .
        docker push friendsofshopware/plugin-uploader:${{ steps.get_version.outputs.VERSION }}
        docker push ghcr.io/friendsofshopware/plugin-uploader:${{ steps.get_version.outputs.VERSION }}
        docker push friendsofshopware/plugin-uploader
        docker push ghcr.io/friendsofshopware/plugin-uploader
